language: php
sudo: false

php:
  - 7
  - 7.1
install:
  - travis_retry composer install --prefer-dist
script:
  - vendor/bin/phpcs src --standard=psr2
  - vendor/bin/phpunit
cache:
  directories:
    - $HOME/.composer/cache
